apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tor-relay
  name: tor-relay
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: tor-relay
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tor-relay
    spec:
      containers:
      - image: quay.io/andysmith/private-tor:latest
        imagePullPolicy: IfNotPresent
        args: ["RELAY"]
        name: tor-relay
        ports:
        - containerPort: 7000
          protocol: TCP
        - containerPort: 9051
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/tor/
          name: torrc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: torrc
          secret:
            secretName: relay-torrc

