apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tor-relay
  name: tor-relay
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: tor-relay
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tor-relay
    spec:
      containers:
      - image: quay.io/andysmith/tor-relay:0.2.8.12
        imagePullPolicy: Always
        command: ["sh", "/entry/docker-entrypoint.sh", "RELAY"]
        name: tor-relay
        ports:
        - containerPort: 7000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/tor/
          name: torrc
        - mountPath: /entry
          name: entry
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: torrc
          secret:
            secretName: relay-torrc
        - name: entry
          configMap:
            name: tor-entry
            defaultMode: 0755

